### ISSUE TITLE
Comparission to other extensions

### ISSUE THREAD

**Issue by Vad1mo** [yholkamp/ovh-docker-volume-plugin#1]
I tried the plugin yesterday and it worked as expected. Even mounting the same volume across multiple VMs worked. 

There is one question left, the you might want to consider adding into the readme.md

**What does this Plugin do different is the comparison to the above**
**Why isn't it possible to use the OpenStack API thats more portable then the OVH one?** 

https://github.com/thecodeteam/rexray/blob/master/.docs/user-guide/storage-providers/openstack.md#cinder

https://github.com/openstack/fuxi

**Comment by yholkamp** [comment]
@Vad1mo I'm sorry for not responding sooner, I've never seen a notification of your issue report and didn't expect to see any at all if I'm being honest. Given the time between your question and my answers I'm guessing they will probably come too late but nevertheless: thanks for giving the plugin a shot and I'm glad it worked as expected.

The creation of this plugin had a couple of origins. First of all I never got the fuxi plugin to work properly and I found the documentation to be rather lacking. [rexray](https://github.com/thecodeteam/rexray) required a number of binaries to be present on the host while my target was to support running the plugin on CoreOS and the container plugin functionality wasn't supported on my docker hosts at the time. Finally [j-griffith's cinder driver](https://github.com/j-griffith/cinder-docker-driver) essentially worked except that I ran in to situations where a volume was 'stuck' and could not be unmounted using the openstack API but this could still be done using the OVH-specific APIs. 

The issues reported as bugs on their mailing list have since been resolved so it's very well possible that you can now reliably use one of the more generic Cinder plugins rather than this plugin.

**Comment by Vad1mo** [comment]
thank you for your answer, I moved now to rexray, as it has a docker container plugin, making easy to install and spin up.  I enabled the [Preemption option](https://rexray.readthedocs.io/en/v0.3.2/user-guide/config/) its mostly not needed but when it is needed it works. quite good so far.

**Comment by yholkamp** [comment]
@Vad1mo no problem and thanks for your update. I'll definitely take a look at their plugin if I'm looking for similar functionality in the future.
